### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ludamad**

### CODE REVIEW

**Review by sirasistant — APPROVED** [review]
Thanks! :D

**Comment by signorecello** [comment]
can we merge this @kobyhallx ?

**Comment by kobyhallx** [comment]
No Description, not sure about this? @ludamad @sirasistant

**Comment by sirasistant** [comment]
It should still be relevant yeah, the issue was that the lib-node folder wasn't accesible since it wasn't on the files array

**Comment by signorecello** [comment]
@kobyhallx can we merge?

**Comment by kobyhallx** [comment]
I'm not sure what we are merging here...?

**Comment by TomAFrench** [comment]
Necessary fix for output of https://github.com/noir-lang/noir-source-resolver/pull/5 to be included in npm package.

**Pull request merged**
